[NEURON][TEST][MXNET] - Update the allowlist for the test to pass (#1871)
* PT1.10, TF2.5 to sdk1.19.0 and mx1.8 to sdk1.18.0

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* enable test

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Add missing files

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change mxnet wheel

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Use the same version of sagemaker-pytorch-inference

With sdk1.17.1 dockerfile the version of sagemaker-pytorch-inference
is 2.0.8. The latest 2.0.10 for some reason throws up following error
InvalidModelException: Model version is not defined.

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix some test

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Bump the dlc major version

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Use mamba instead of mini conda

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* add tf 1.15

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* add torchserve vuln

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* add torchserve vuln to safety check

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* get_dockerfile_path_for_image add neuron sdk version

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* fix the get_dockerfile_path_for_image

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* fix the ecr scan

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* fix the scan

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Take care of review comments

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* change python version

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* move back to python 3.7.10

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* revert config changes

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change the allowlist

Signed-off-by: Venky Natham <vrnatham@amazon.com>