[NEURON][TF][BUILD] - Neuron SDK 2.5.0 release (#2463)
* First commit for tf2.8 for sdk 2.5.0

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Enable test

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Use focal instead of bionic

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Add runtime-lib installation

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Changes for ecs test

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change the buildspec

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* eks test changes

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change ports for neuron

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change the sync command

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Use the right model for tf

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Use the original model for tf2.8 also

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix dlc labels issue

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Add allowlist json

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix the safety report

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Move to 2.8.0 instead of 2.8.2

With 2.8.2 seeing the following error

```
>>> import tensorflow_neuron
2022-12-08 22:22:22.442321: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] libneuronxla path is: /home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/libneuronxla/libtpu.so
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe                                                                                                Traceback (most recent call last):                                                                                                                                                      File "<stdin>", line 1, in <module>                                                                                                                                                   File "/home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/tensorflow_neuron/__init__.py", line 18, in <module>                                                                        from tensorflow_neuron.python._trace import trace                                                                                                                                   File "/home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/tensorflow_neuron/python/_trace.py", line 19, in <module>                                                                   from tensorflow.core.protobuf import config_pb2                                                                                                                                     File "/home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 51, in <module>                                                                               from tensorflow.python.tools import module_util as _module_util                                                                                                                     File "/home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>                                                                        from tensorflow.python.eager import context                                                                                                                                         File "/home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>                                                                   from tensorflow.python.client import pywrap_tf_session                                                                                                                              File "/home/ubuntu/38_tf28_venv/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py", line 19, in <module>                                                        from tensorflow.python.client._pywrap_tf_session import *                                                                                                                         ImportError: SystemError: <built-in method __contains__ of dict object at 0x7f9b1b003c80> returned a result with an error set                                                         >>>
```

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change to 2.8.0

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change safety for 2.8.0

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Change the scan allowlist for 2.8.0

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Remove ecr scan

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* fix dependancy check

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Add the ecr scan allowlist

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Add apt upgrade

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Use mnist

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Add new line

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix the dlc label test after tf1.15 commit

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix the allowlist

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix the json allowlist file

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Fix dependancy check

Signed-off-by: Venky Natham <vrnatham@amazon.com>

* Revert test changes

Signed-off-by: Venky Natham <vrnatham@amazon.com>

Signed-off-by: Venky Natham <vrnatham@amazon.com>
Co-authored-by: Mike Schneider <104035434+xncqr@users.noreply.github.com>