Upgrade mamba version due to ImportError: cannot import name generate_parser from conda.cli.main (#4311)
* Upgrade mamba version due to ImportError: cannot import name generate_parser from conda.cli.main

* build training

* revert toml