AI changes made during Kiro-cli session --- X-AI-Tool: Kiro-cli X-AI-Handle-Time-Seconds: 33 X-AI-Prompt: INFO     sagemaker:session.py:1270 Creating training-job with name: xgb-netiso-script-1wjwu25pdvhouel81ii591cs0jzg6m55n8tkmjtd168k8 FAILED                                                                   [100%]
=================================== FAILURES ===================================
____________________ TestNetworkIsolation.test_script_mode _____________________
xgboost/e2e/test_network_isolation.py:75: in test_script_mode
estimator.fit(channels, job_name=job_name)
../.venv/lib64/python3.12/site-packages/sagemaker/telemetry/telemetry_logging.py:171: in wrapper
raise caught_ex
../.venv/lib64/python3.12/site-packages/sagemaker/telemetry/telemetry_logging.py:142: in wrapper
response = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
../.venv/lib64/python3.12/site-packages/sagemaker/workflow/pipeline_context.py:346: in wrapper
return run_func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib64/python3.12/site-packages/sagemaker/estimator.py:1429: in fit
self.latest_training_job.wait(logs=logs)
../.venv/lib64/python3.12/site-packages/sagemaker/estimator.py:2831: in wait
self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
../.venv/lib64/python3.12/site-packages/sagemaker/session.py:6379: in logs_for_job
_logs_for_job(self, job_name, wait, poll, log_type, timeout)
../.venv/lib64/python3.12/site-packages/sagemaker/session.py:9010: in _logs_for_job
_check_job_status(job_name, description, "TrainingJobStatus")
../.venv/lib64/python3.12/site-packages/sagemaker/session.py:9074: in _check_job_status
raise exceptions.UnexpectedStatusException(
E   sagemaker.exceptions.UnexpectedStatusException: Error for Training job xgb-netiso-script-1wjwu25pdvhouel81ii591cs0jzg6m55n8tkmjtd168k8: Failed. Reason: AlgorithmError: framework error:
E   Traceback (most recent call last):
E     File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_trainer.py", line 84, in train
E       entrypoint()
E     File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 102, in main
E       train(framework.training_env())
E     File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 87, in train
E       framework.modules.run_module(
E     File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_modules.py", line 290, in run_module
E       _files.download_and_extract(uri, _env.code_dir)
E     File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_files.py", line 140, in download_and_extract
E       elif tarfile.is_tarfile(uri):
E     File "/miniconda3/lib/python3.10/tarfile.py", line 2914, in is_tarfile
E       t = open(name)
E     File "/miniconda3/lib/python3.10/tarfile.py", line 1853, in open
E       return func(name, "r", fileobj, **kwargs)
E     File "/miniconda3/lib/python3.1. Check troubleshooting guide for common errors: https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sdk-troubleshooting.html
----------------------------- Captured stdout call -----------------------------
2026-04-02 22:05:16 Starting - Starting the training job...
2026-04-02 22:05:32 Starting - Preparing the instances for training...
2026-04-02 22:06:12 Downloading - Downloading the training image...../miniconda3/lib/python3.10/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
import pkg_resources
[2026-04-02:22:06:57:INFO] Imported framework sagemaker_xgboost_container.training
[2026-04-02:22:06:57:INFO] No GPUs detected (normal if no gpus installed)
[2026-04-02:22:06:57:INFO] Invoking user training script.
[2026-04-02:22:06:57:ERROR] Reporting training FAILURE
[2026-04-02:22:06:57:ERROR] framework error:
Traceback (most recent call last):
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_trainer.py", line 84, in train
entrypoint()
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 102, in main
train(framework.training_env())
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 87, in train
framework.modules.run_module(
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_modules.py", line 290, in run_module
_files.download_and_extract(uri, _env.code_dir)
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_files.py", line 140, in download_and_extract
elif tarfile.is_tarfile(uri):
File "/miniconda3/lib/python3.10/tarfile.py", line 2914, in is_tarfile
t = open(name)
File "/miniconda3/lib/python3.10/tarfile.py", line 1853, in open
return func(name, "r", fileobj, **kwargs)
File "/miniconda3/lib/python3.10/tarfile.py", line 1919, in gzopen
fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
File "/miniconda3/lib/python3.10/gzip.py", line 174, in __init__
fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/code/sourcedir.tar.gz'
[Errno 2] No such file or directory: '/opt/ml/input/data/code/sourcedir.tar.gz'
/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
import pkg_resources
[2026-04-02:22:06:59:INFO] Imported framework sagemaker_xgboost_container.training
[2026-04-02:22:06:59:INFO] No GPUs detected (normal if no gpus installed)
[2026-04-02:22:06:59:INFO] Invoking user training script.
[2026-04-02:22:06:59:ERROR] Reporting training FAILURE
[2026-04-02:22:06:59:ERROR] framework error:
Traceback (most recent call last):
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_trainer.py", line 84, in train
entrypoint()
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 102, in main
train(framework.training_env())
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 87, in train
framework.modules.run_module(
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_modules.py", line 290, in run_module
_files.download_and_extract(uri, _env.code_dir)
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_files.py", line 140, in download_and_extract
elif tarfile.is_tarfile(uri):
File "/miniconda3/lib/python3.10/tarfile.py", line 2914, in is_tarfile
t = open(name)
File "/miniconda3/lib/python3.10/tarfile.py", line 1853, in open
return func(name, "r", fileobj, **kwargs)
File "/miniconda3/lib/python3.10/tarfile.py", line 1919, in gzopen
fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
File "/miniconda3/lib/python3.10/gzip.py", line 174, in __init__
fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/input/data/code/sourcedir.tar.gz'
[Errno 2] No such file or directory: '/opt/ml/input/data/code/sourcedir.tar.gz'

2026-04-02 22:07:17 Training - Training image download completed. Training in progress.
2026-04-02 22:07:17 Uploading - Uploading generated training model
2026-04-02 22:07:17 Failed - Training job failed