AI changes made during Kiro-cli session --- X-AI-Tool: Kiro-cli X-AI-Handle-Time-Seconds: 49 X-AI-Prompt: NFO     sagemaker:session.py:1270 Creating training-job with name: xgb-select-train-bkgoejp1l8stxhg ERROR                                                                    [ 20%] xgboost/e2e/test_e2e_selectable.py::TestSelectableInference::test_json_accept ERROR [ 40%] xgboost/e2e/test_e2e_selectable.py::TestSelectableInference::test_jsonlines_accept ERROR [ 60%] xgboost/e2e/test_e2e_selectable.py::TestSelectableInference::test_csv_nans_misconfigured_keys ERROR [ 80%] xgboost/e2e/test_e2e_selectable.py::TestSelectableInference::test_batch_transform_csv ERROR [100%]
==================================== ERRORS ====================================
__________ ERROR at setup of TestSelectableInference.test_csv_accept ___________
xgboost/e2e/test_e2e_selectable.py:28: in selectable_model
_, _, desc = run_training_job(
xgboost/e2e/conftest.py:121: in run_training_job
estimator.fit(channels, job_name=job_name)
../.venv/lib64/python3.12/site-packages/sagemaker/telemetry/telemetry_logging.py:171: in wrapper
raise caught_ex
../.venv/lib64/python3.12/site-packages/sagemaker/telemetry/telemetry_logging.py:142: in wrapper
response = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
../.venv/lib64/python3.12/site-packages/sagemaker/workflow/pipeline_context.py:346: in wrapper
return run_func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
../.venv/lib64/python3.12/site-packages/sagemaker/estimator.py:1429: in fit
self.latest_training_job.wait(logs=logs)
../.venv/lib64/python3.12/site-packages/sagemaker/estimator.py:2831: in wait
self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
../.venv/lib64/python3.12/site-packages/sagemaker/session.py:6379: in logs_for_job
_logs_for_job(self, job_name, wait, poll, log_type, timeout)
../.venv/lib64/python3.12/site-packages/sagemaker/session.py:9010: in _logs_for_job
_check_job_status(job_name, description, "TrainingJobStatus")
../.venv/lib64/python3.12/site-packages/sagemaker/session.py:9074: in _check_job_status
raise exceptions.UnexpectedStatusException(
E   sagemaker.exceptions.UnexpectedStatusException: Error for Training job xgb-select-train-bkgoejp1l8stxhg: Failed. Reason: AlgorithmError: framework error:
E   Traceback (most recent call last):
E     File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 367, in train_job
E       bst = xgb.train(
E     File "/miniconda3/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
E       return func(**kwargs)
E     File "/miniconda3/lib/python3.10/site-packages/xgboost/training.py", line 184, in train
E       if cb_container.after_iteration(bst, i, dtrain, evals):
E     File "/miniconda3/lib/python3.10/site-packages/xgboost/callback.py", line 264, in after_iteration
E       score: str = model.eval_set(evals, epoch, self.metric, self._output_margin)
E     File "/miniconda3/lib/python3.10/site-packages/xgboost/core.py", line 2352, in eval_set
E       _check_call(
E     File "/miniconda3/lib/python3.10/site-packages/xgboost/core.py", line 310, in _check_call
E       raise XGBoostError(py_str(_LIB.XGBGetLastError()))
E   xgboost.core.XGBoostError: [00:48:24] /workspace/src/metric/multiclass_metric.cu:34: Check failed: label_error. Check troubleshooting guide for common errors: https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sdk-troubleshooting.html
---------------------------- Captured stdout setup -----------------------------
2026-04-03 00:46:42 Starting - Starting the training job...
2026-04-03 00:46:57 Starting - Preparing the instances for training...
2026-04-03 00:47:39 Downloading - Downloading the training image...
2026-04-03 00:48:15 Training - Training image download completed. Training in progress.../miniconda3/lib/python3.10/site-packages/sagemaker_containers/_server.py:22: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
import pkg_resources
[2026-04-03:00:48:24:INFO] Imported framework sagemaker_xgboost_container.training
[2026-04-03:00:48:24:INFO] Failed to parse hyperparameter objective value multi:softprob to Json.
Returning the value itself
[2026-04-03:00:48:24:INFO] No GPUs detected (normal if no gpus installed)
[2026-04-03:00:48:24:INFO] Running XGBoost Sagemaker in algorithm mode
[2026-04-03:00:48:24:INFO] Determined 0 GPU(s) available on the instance.
[2026-04-03:00:48:24:INFO] Determined delimiter of CSV input is ','
[2026-04-03:00:48:24:INFO] Determined delimiter of CSV input is ','
[2026-04-03:00:48:24:INFO] Determined delimiter of CSV input is ','
[2026-04-03:00:48:24:INFO] File path /opt/ml/input/data/train of input files
[2026-04-03:00:48:24:INFO] Making smlinks from folder /opt/ml/input/data/train to folder /tmp/sagemaker_xgboost_input_data
[2026-04-03:00:48:24:INFO] creating symlink between Path /opt/ml/input/data/train/iris_train.csv and destination /tmp/sagemaker_xgboost_input_data/iris_train.csv1156569188642389932
[2026-04-03:00:48:24:INFO] files path: /tmp/sagemaker_xgboost_input_data
[2026-04-03:00:48:24:INFO] Determined delimiter of CSV input is ','
[2026-04-03:00:48:24:INFO] File path /opt/ml/input/data/validation of input files
[2026-04-03:00:48:24:INFO] Making smlinks from folder /opt/ml/input/data/validation to folder /tmp/sagemaker_xgboost_input_data
[2026-04-03:00:48:24:INFO] creating symlink between Path /opt/ml/input/data/validation/iris_test.csv and destination /tmp/sagemaker_xgboost_input_data/iris_test.csv-2536577083435342830
[2026-04-03:00:48:24:INFO] creating symlink between Path /opt/ml/input/data/validation/iris_sample_selectable.csv and destination /tmp/sagemaker_xgboost_input_data/iris_sample_selectable.csv-5583408458500166580
[2026-04-03:00:48:24:INFO] files path: /tmp/sagemaker_xgboost_input_data
[2026-04-03:00:48:24:INFO] Determined delimiter of CSV input is ','
[2026-04-03:00:48:24:INFO] Single node training.
[2026-04-03:00:48:24:INFO] TRAIN_JOB_DEBUG: Received is_master=True
TRAIN_JOB_DEBUG: Received is_master=True
[2026-04-03:00:48:24:INFO] Train matrix has 1050 rows and 5 columns
[2026-04-03:00:48:24:INFO] Validation matrix has 512 rows
[2026-04-03:00:48:24:INFO] CALLBACK_SETUP_DEBUG: save_model_on_termination=false, is_master=True
[2026-04-03:00:48:24:INFO] CALLBACK_SKIPPING save_model_on_termination=false, is_master=True)
[00:48:24] DEBUG: /workspace/src/gbm/gbtree.cc:131: Using tree method: 0
[00:48:24] DEBUG: /workspace/src/data/simple_dmatrix.cc:182: Generating new Gradient Index.
[00:48:24] ======== Monitor (0): HostSketchContainer ========
[00:48:24] AllReduce: 7.7e-05s, 1 calls @ 77us
[00:48:24] MakeCuts: 9.2e-05s, 1 calls @ 92us
[00:48:24] PushRowPage: 4.9e-05s, 1 calls @ 49us
[2026-04-03:00:48:24:ERROR] Reporting training FAILURE
[2026-04-03:00:48:24:ERROR] framework error:
Traceback (most recent call last):
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 367, in train_job
bst = xgb.train(
File "/miniconda3/lib/python3.10/site-packages/xgboost/core.py", line 729, in inner_f
return func(**kwargs)
File "/miniconda3/lib/python3.10/site-packages/xgboost/training.py", line 184, in train
if cb_container.after_iteration(bst, i, dtrain, evals):
File "/miniconda3/lib/python3.10/site-packages/xgboost/callback.py", line 264, in after_iteration
score: str = model.eval_set(evals, epoch, self.metric, self._output_margin)
File "/miniconda3/lib/python3.10/site-packages/xgboost/core.py", line 2352, in eval_set
_check_call(
File "/miniconda3/lib/python3.10/site-packages/xgboost/core.py", line 310, in _check_call
raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [00:48:24] /workspace/src/metric/multiclass_metric.cu:34: Check failed: label_error >= 0 && label_error < static_cast<int32_t>(n_class): MultiClassEvaluation: label must be in [0, num_class), num_class=3 but found 128 in label
Stack trace:
[bt] (0) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x2a6e7c) [0x7ff853544e7c]
[bt] (1) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0xd9c013) [0x7ff85403a013]
[bt] (2) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x6b33b6) [0x7ff8539513b6]
[bt] (3) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x68c230) [0x7ff85392a230]
[bt] (4) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGBoosterEvalOneIter+0x1d6) [0x7ff85345d6a6]
[bt] (5) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(+0x702a) [0x7ff87ca5e02a]
[bt] (6) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(+0x64a9) [0x7ff87ca5d4a9]
[bt] (7) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(ffi_call+0xdd) [0x7ff87ca5dbbd]
[bt] (8) /miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x8c7b) [0x7ff87ca6bc7b]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/miniconda3/lib/python3.10/site-packages/sagemaker_containers/_trainer.py", line 84, in train
entrypoint()
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 102, in main
train(framework.training_env())
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 98, in train
run_algorithm_mode()
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/training.py", line 64, in run_algorithm_mode
sagemaker_train(
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 278, in sagemaker_train
train_job(**train_args)
File "/miniconda3/lib/python3.10/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 464, in train_job
raise exc.UserError(str(e))
sagemaker_algorithm_toolkit.exceptions.UserError: [00:48:24] /workspace/src/metric/multiclass_metric.cu:34: Check failed: label_error >= 0 && label_error < static_cast<int32_t>(n_class): MultiClassEvaluation: label must be in [0, num_class), num_class=3 but found 128 in label
Stack trace:
[bt] (0) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x2a6e7c) [0x7ff853544e7c]
[bt] (1) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0xd9c013) [0x7ff85403a013]
[bt] (2) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x6b33b6) [0x7ff8539513b6]
[bt] (3) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x68c230) [0x7ff85392a230]
[bt] (4) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGBoosterEvalOneIter+0x1d6) [0x7ff85345d6a6]
[bt] (5) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(+0x702a) [0x7ff87ca5e02a]
[bt] (6) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(+0x64a9) [0x7ff87ca5d4a9]
[bt] (7) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(ffi_call+0xdd) [0x7ff87ca5dbbd]
[bt] (8) /miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x8c7b) [0x7ff87ca6bc7b]
[00:48:24] /workspace/src/metric/multiclass_metric.cu:34: Check failed: label_error >= 0 && label_error < static_cast<int32_t>(n_class): MultiClassEvaluation: label must be in [0, num_class), num_class=3 but found 128 in label
Stack trace:
[bt] (0) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x2a6e7c) [0x7ff853544e7c]
[bt] (1) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0xd9c013) [0x7ff85403a013]
[bt] (2) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x6b33b6) [0x7ff8539513b6]
[bt] (3) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(+0x68c230) [0x7ff85392a230]
[bt] (4) /miniconda3/lib/python3.10/site-packages/xgboost/lib/libxgboost.so(XGBoosterEvalOneIter+0x1d6) [0x7ff85345d6a6]
[bt] (5) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(+0x702a) [0x7ff87ca5e02a]
[bt] (6) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(+0x64a9) [0x7ff87ca5d4a9]
[bt] (7) /miniconda3/lib/python3.10/lib-dynload/../../libffi.so.8(ffi_call+0xdd) [0x7ff87ca5dbbd]
[bt] (8) /miniconda3/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x8c7b) [0x7ff87ca6bc7b]
[00:48:24] ======== Monitor (0): Learner ========
[00:48:24] Configure: 0s, 1 calls @ 0us
/miniconda3/lib/pytho